name: chamada_automatica
description: Protótipo N2 (V2) — modo aluno único com rodadas automáticas
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^13.0.3

  #Atualizacoes na n3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  share_plus: ^7.2.0

  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


